---
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: badcfda739ac5d5e538299664c7439849c785c6c  # frozen: v8.26.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: 192ad822316c3a22fb3d3cc8aa6eafa0b8488360  # frozen: v0.45.0
    hooks:
      - id: markdownlint

